version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    restart: always
    working_dir: /nomisma/web
    ports:
      - "8080:8080"
    links:
      - "back: back"
    environment:
      - BACKEND_HOST=back
  back:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    ports:
      - "4000:4000"